# Custom style: BloodyMary_v3
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#660000',
    'bg2': '#470000',
    'bg3': '#440000',
    'bg4': '#470000',
    'border1': '#770000',
    'border2': '#770000',
    'text1': 'white',
    'text2': '#aa0000',
    'tab_bg': '#550000',
    'tab_sel': '#880000',
    'accent': '#2196f3',
    'canvas': '#550000',
    'danger': '#c62828',
    'danger_hover': '#eb3535',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
