# Custom style: BloodyMary_v3
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#660000',
    'bg2': '#470000',
    'bg3': '#440000',
    'bg4': '#470000',
    'border1': '#770000',
    'border2': '#770000',
    'text1': 'white',
    'text2': '#aa0000',
    'crit1': '#aa0000',
    'tab_bg': '#550000',
    'tab_sel': '#880000',
    'accent': '#2196f3',
    'score': 'yellow',
    'score_border': '#550000',
    'canvas': '#550000',
    'pos': '#4CAF50',
    'pos_bg': '#2d5016',
    'pos_hover': '#356019',
    'neg': '#c62828',
    'neg_hover': '#eb3535',
    'neg_bg': '#5c1a1a',
    'neg_bg_hover': '#6b2020',
}


# Styles as functions |Marker for style_editor, don't edit or remove
def card_style():
    return f"""
        ImageCard {{
            border: 2px solid {COLORS['border1']};
            border-radius: 12px;
            background: {COLORS['bg2']};
        }}
    """

def card_border_pos():
    return f"""
        ImageCard {{
            border: 2px solid {COLORS['pos']};
            border-radius: 12px;
            background: {COLORS['bg2']};
        }}
    """

def card_border_green():
    return card_border_pos()

def card_border_red():
    return f"""
        ImageCard {{
            border: 2px solid {COLORS['neg']};
            border-radius: 12px;
            background: {COLORS['bg2']};
        }}
    """

def close_button():
    return f"""
        QPushButton {{
            background: {COLORS['neg']};
            color: {COLORS['text1']};
            font-weight: bold;
            font-size: 18px;
        }}
        QPushButton:hover {{
            background: {COLORS['neg_hover']};
        }}
    """

def checkpoint_label():
    return f"font-size: 14px; font-weight: bold; color: {COLORS['text1']}; background: transparent;"

def score_label():
    return f"""
        color: {COLORS['score']};
        font-size: 20px;
        font-weight: bold;
        border: 2px solid {COLORS['score_border']};
        border-radius: 6px;
        background: transparent;
    """

def criterion_button_neutral():
    return f"""
        QPushButton {{
            background: {COLORS['bg3']};
            color: {COLORS['crit1']};
            border: 1px solid {COLORS['crit1']};
            border-radius: 6px;
        }}
        QPushButton:hover {{
            background: {COLORS['border1']};
        }}
    """

def criterion_button_green():
    return f"""
        QPushButton {{
            background: {COLORS['pos_bg']};
            color: {COLORS['pos']};
            border: 1px solid {COLORS['pos']};
            border-radius: 6px;
        }}
        QPushButton:hover {{
            background: {COLORS['pos_hover']};
        }}
    """

def criterion_button_red():
    return f"""
        QPushButton {{
            background: {COLORS['neg_bg']};
            color: {COLORS['neg_hover']};
            border: 1px solid {COLORS['neg']};
            border-radius: 6px;
        }}
        QPushButton:hover {{
            background: {COLORS['neg_bg_hover']};
        }}
    """

def main_theme():
    return f"""
        QWidget {{
            background-color: {COLORS['tab_bg']};
            color: {COLORS['text1']};
        }}
        QGroupBox {{
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border2']};
            border-radius: 6px;
            margin-top: 8px;
            padding-top: 8px;
        }}
        QGroupBox::title {{
            color: {COLORS['text1']};
            subcontrol-origin: margin;
            left: 10px;
            padding: 0 3px;
        }}
        QPushButton {{
            background: {COLORS['bg3']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border2']};
            border-radius: 6px;
            padding: 5px 10px;
        }}
        QPushButton:hover {{
            background: {COLORS['border1']};
        }}
        QLabel {{
            color: {COLORS['text1']};
        }}
        QSlider::groove:horizontal {{
            background: {COLORS['bg3']};
            height: 8px;
            border-radius: 4px;
        }}
        QSlider::handle:horizontal {{
            background: {COLORS['accent']};
            width: 18px;
            margin: -5px 0;
            border-radius: 9px;
        }}
        QScrollArea {{
            border: none;
            background: {COLORS['tab_bg']};
        }}
    """

def drop_zone():
    return f"""
        QLabel {{
            border: 3px dashed {COLORS['border2']};
            background: {COLORS['bg4']};
            color: {COLORS['text2']};
            font-size: 16px;
            font-weight: bold;
            min-height: 80px;
            border-radius: 8px;
        }}
        QLabel:hover {{
            border-color: {COLORS['accent']};
            color: {COLORS['accent']};
        }}
    """

def clear_button():
    return f"""
        QPushButton {{
            background: {COLORS['neg']};
            color: {COLORS['text1']};
            font-weight: bold;
        }}
        QPushButton:hover {{
            background: {COLORS['neg_hover']};
        }}
    """

def main_window():
    return f"""
        QMainWindow {{
            background-color: {COLORS['bg1']};
        }}
        QTabWidget::pane {{
            border: 1px solid {COLORS['border1']};
            background: {COLORS['tab_bg']};
            border-radius: 8px;
        }}
        QTabBar::tab {{
            background: {COLORS['bg2']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border1']};
            padding: 8px 16px;
            margin-right: 2px;
            border-top-left-radius: 8px;
            border-top-right-radius: 8px;
        }}
        QTabBar::tab:selected {{
            background: {COLORS['tab_sel']};
            border: 1px solid {COLORS['tab_sel']};
            border-bottom: 1px solid {COLORS['tab_sel']};
        }}
        QTabBar::tab:!selected:hover {{
            background: {COLORS['tab_bg']};
        }}
    """

def add_tab_button():
    return f"""
        QPushButton {{
            background: {COLORS['bg3']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border2']};
            border-radius: 6px;
            font-weight: bold;
            font-size: 18px;
        }}
        QPushButton:hover {{
            background: {COLORS['border1']};
        }}
    """

def remove_tab_button():
    return f"""
        QPushButton {{
            background: {COLORS['neg']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['neg']};
            border-radius: 6px;
            font-weight: bold;
            font-size: 18px;
        }}
        QPushButton:hover {{
            background: {COLORS['neg_hover']};
        }}
    """

def fullscreen_background():
    return f"background-color: {COLORS['canvas']};"

def fullscreen_close_button():
    return f"""
        QPushButton {{
            background: {COLORS['neg']};
            color: {COLORS['text1']};
            border: none;
            border-radius: 6px;
            font-size: 16px;
            font-weight: bold;
        }}
        QPushButton:hover {{
            background: {COLORS['neg_hover']};
        }}
    """

def fullscreen_label():
    return f"color: {COLORS['text1']}; font-size: 14px; margin-left: 20px;"

def fullscreen_combo():
    return f"""
        QComboBox {{
            background: {COLORS['bg3']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border2']};
            border-radius: 6px;
            padding: 5px 10px;
            min-width: 150px;
            font-size: 14px;
        }}
        QComboBox::drop-down {{
            border: none;
            width: 20px;
        }}
        QComboBox::down-arrow {{
            image: none;
            border-left: 5px solid transparent;
            border-right: 5px solid transparent;
            border-top: 5px solid {COLORS['text1']};
            width: 0px;
            height: 0px;
        }}
        QComboBox QAbstractItemView {{
        	background: {COLORS['bg3']};
            color: {COLORS['text1']};
        }}
        QComboBox QAbstractItemView::item:selected {{
            background: {COLORS['neg']};
        }}
    """

def fullscreen_info():
    return f"color: {COLORS['text1']}; font-size: 14px; font-weight: bold; padding: 10px;"

def fullscreen_info_selectable():
    return (f"color: {COLORS['text1']}; font-size: 14px; font-weight: bold; padding: 10px; "
            f"selection-background-color: {COLORS['accent']}; selection-color: {COLORS['text1']};")

def image_container():
    return f"background: {COLORS['canvas']};"

def options_button():
    return f"""
        QPushButton {{
            background: {COLORS['bg3']};
            color: {COLORS['text1']};
            border: 1px solid {COLORS['border2']};
            border-radius: 6px;
            font-weight: bold;
        }}
        QPushButton:hover {{
            background: {COLORS['border1']};
        }}
    """