# Custom style: dark_copy
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#2e2e2e',
    'bg2': '#2b2b2b',
    'bg3': '#333333',
    'bg4': '#2b2b2b',
    'border1': '#444',
    'border2': '#555',
    'text1': 'white',
    'text2': '#888',
    'crit1': '#888',
    'tab_bg': '#1e1e1e',
    'tab_sel': '#444',
    'accent': '#2196F3',
    'score': 'yellow',
    'score_border': '#1e1e1e',
    'canvas': 'black',
    'pos': '#4CAF50',
    'pos_bg': '#2d5016',
    'pos_hover': '#356019',
    'neg': '#c62828',
    'neg_hover': '#eb3535',
    'neg_bg': '#5c1a1a',
    'neg_bg_hover': '#6b2020',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
