# Custom style: lite_copy
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#ffffff',
    'bg2': '#888888',
    'bg3': '#3a3a3a',
    'bg4': '#bababa',
    'border1': '#666666',
    'border2': '#888888',
    'text1': '#ffffff',
    'text2': '#888888',
    'crit1': '#888888',
    'tab_bg': '#cccccc',
    'tab_sel': '#cccccc',
    'accent': '#2196F3',
    'score': 'yellow',
    'score_border': '#1e1e1e',
    'canvas': '#444444',
    'pos': '#4CAF50',
    'pos_bg': '#2d5016',
    'pos_hover': '#356019',
    'neg': '#c62828',
    'neg_hover': '#eb3535',
    'neg_bg': '#5c1a1a',
    'neg_bg_hover': '#6b2020',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
