# Custom style: light_v3
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#ffffff',
    'bg2': '#aaaaaa',
    'bg3': '#ff3300',
    'bg4': '#aaaaaa',
    'border1': '#666666',
    'border2': '#888888',
    'text1': '#ffffff',
    'text2': '#888888',
    'crit1': '#ffffff',
    'tab_bg': '#cccccc',
    'tab_sel': '#cccccc',
    'accent': '#ff6600',
    'score': 'yellow',
    'score_border': '#888888',
    'canvas': '#444444',
    'danger': '#c62828',
    'danger_hover': '#eb3535',
    'pos': '#4CAF50',
    'pos_bg': '#2d5016',
    'pos_hover': '#356019',
    'neg': '#ef5350',
    'neg_bg': '#5c1a1a',
    'neg_hover': '#7c2525',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
