# Custom style: light_v2
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#ffffff',
    'bg2': '#888888',
    'bg3': '#3a3a3a',
    'bg4': '#bababa',
    'border1': '#666666',
    'border2': '#888888',
    'text1': '#ffffff',
    'text2': '#888888',
    'tab_bg': '#cccccc',
    'tab_sel': '#cccccc',
    'accent': '#2196F3',
    'canvas': '#444444',
    'danger': '#c62828',
    'danger_hover': '#eb3535',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
