# Custom style: v4
# Auto-generated by Style Editor

COLORS = {
    'bg1': '#ffffff',
    'bg2': '#aaaaaa',
    'bg3': '#993300',
    'bg4': '#aaaaaa',
    'border1': '#666666',
    'border2': '#888888',
    'text1': '#ffffff',
    'text2': '#888888',
    'tab_bg': '#cccccc',
    'tab_sel': '#cccccc',
    'accent': '#ff6600',
    'canvas': '#444444',
    'danger': '#c62828',
    'danger_hover': '#eb3535',
}

from pathlib import Path as _Path
exec((_Path(__file__).parent.parent / 'styles_base_layout.py').read_text(encoding='utf-8'))
