# Module style override: new1
# Auto-generated by Style Editor

COLORS_EXTRA = {
    'score': '#00ffff',
    'score_border': '#1e1e1e',
    'crit1': '#55ffff',
    'pos': '#4CAF50',
    'pos_bg': '#2d5016',
    'pos_hover': '#356019',
    'neg': '#c62828',
    'neg_bg': '#5c1a1a',
    'neg_hover': '#6b2020',
    'ckpt_label': 'white',
}
